In [ ]:
# Numpy numeric computing tool , it is opensource
# powerful n dimensional arrays


In [ ]:
# arrays - homogenous , index
# array can be one dimension and n -dimension

In [ ]:
l=[10,20,30,40]
l1=[]
for item in l:
  l1.append(item*5)
print(l1)

[50, 100, 150, 200]


In [ ]:
# pip install numpy  , pip3 install numpy  , python -m pip install numpy
# !pip install numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([10,20,30,40])
print('type of arr',type(arr))
print(arr)
print(arr*5)
print('Dimension of array',arr.ndim)
print('data type of item of array',arr.dtype)

type of arr <class 'numpy.ndarray'>
[10 20 30 40]
[ 50 100 150 200]
Dimension of array 1
data type of item of array int64


In [ ]:
arr=np.array([10,20,30,40],dtype=np.float64)
print('data type of item of array',arr.dtype)
print('size of the item in array',arr.itemsize)
print("no of item in array",len(arr))
print('float arr',arr)

data type of item of array float64
size of the item in array 8
no of item in array 4
float arr [10. 20. 30. 40.]


In [ ]:
arr1 =np.asarray([100,200,300])
print('type of arr1',type(arr1))

type of arr1 <class 'numpy.ndarray'>


In [ ]:
mat = np.array([[10,20,30],[40,50,60],[70,80,90]])
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
print('lenght of mat ',len(mat))
print('shape of array',mat.shape)
print('dimension of mat',mat.ndim)

lenght of mat  3
shape of array (3, 3)
dimension of mat 2


In [ ]:
zeroMat = np.zeros((4,3),dtype=np.int32)
print('zero matrix')
print(zeroMat)

zero matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
oneMat = np.ones((4,3),dtype=np.int32)
print('one matrix')
print(oneMat)

one matrix
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
n=int(input("enter no to fill mat"))
print(oneMat*n)

enter no to fill mat8
[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [ ]:
n=int(input("enter no to fill mat"))
fillMat = np.full((3,3),n,dtype=np.int32)  # full(shape, valuetofill , datatype)
print('filled matrix')
print(fillMat)

enter no to fill mat5
filled matrix
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# identical matrix
identical =np.eye(4,dtype=np.int32)
print(identical)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
randomarr=np.random.random((3,2))
print("Random array \n",randomarr)

Random array 
 [[0.64358964 0.31042859]
 [0.17047737 0.97900854]
 [0.32599458 0.38236964]]


In [ ]:
randomintarr = np.random.randint(low=10,high=50,size=(3,3))
print('random int arr \n',randomintarr)

random int arr 
 [[44 41 26]
 [18 31 32]
 [16 28 30]]


In [ ]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# transpose the array - convert rows into columns
tMat = mat.T
print('transposed matrix  \n',tMat)

transposed matrix  
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
tMat1 = mat.transpose()
print('transposed matrix  \n',tMat1)

transposed matrix  
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
#reshape and resize
# reshape() will change the shape of array
# it will create a new array
# no of elements should be same
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
rarr= np.reshape(mat,(1,9))  # np.reshape(arr,newshape)
print('reshape array',rarr)
print('dim',rarr.ndim)

reshape array [[10 20 30 40 50 60 70 80 90]]
dim 2


In [ ]:
rarr= np.reshape(mat,(9,1))  # np.reshape(arr,newshape)
print('reshape array',rarr)
print('dim',rarr.ndim)

reshape array [[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
dim 2


In [ ]:
mat1 = np.array([[100,200,300],[400,500,600],[700,800,900]])
mat1

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [ ]:
mat1.shape=((1,9))  # it will reshape the original array
print(mat1)

[[100 200 300 400 500 600 700 800 900]]


In [ ]:
mat1

array([[100, 200, 300, 400, 500, 600, 700, 800, 900]])

In [ ]:
rarr2=np.reshape(mat,(-1,1))
print(rarr2)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [ ]:
rarr2=np.reshape(mat,(1,-1))  # it will create 1 row and columns = total no of elements in the array
print(rarr2)

[[10 20 30 40 50 60 70 80 90]]


In [ ]:
#resize
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
resizeArr=np.resize(mat,(2,2))  # Return a new array with the specified shape.
print('resize array 2 *2  \n', resizeArr)

resize array 2 *2  
 [[10 20]
 [30 40]]


In [ ]:
resizeArr=np.resize(mat,(5,5))  # Return a new array with the specified shape.
print('resize array 5 *5  \n', resizeArr)

resize array 5 *5  
 [[10 20 30 40 50]
 [60 70 80 90 10]
 [20 30 40 50 60]
 [70 80 90 10 20]
 [30 40 50 60 70]]


In [ ]:
# convert array into 1 dim
oneDimArray = mat.ravel()  # Return a flattened array.
print(oneDimArray)
print('shape of array',oneDimArray.shape)
print('dim of arra', oneDimArray.ndim)

[10 20 30 40 50 60 70 80 90]
shape of array (9,)
dim of arra 1


In [ ]:
#arange(start,end,step ) it will genereate 1 dim array in given range excluding the end
arr = np.arange(10,20,5)
print(arr)

[10 15]


In [ ]:
arr=np.arange(100,90,-1)
print(arr)

[100  99  98  97  96  95  94  93  92  91]


In [ ]:
arr=arr.reshape((5,2))
print(arr)

[[100  99]
 [ 98  97]
 [ 96  95]
 [ 94  93]
 [ 92  91]]


In [ ]:
# access array element arrayname[index] , arrayname[row][columns], array[x][y][z]...[n]
print('value at 0 row and 0 columns',arr[0][0])
print(arr[3][1])
# IndexError : if we try to access index out of bound

value at 0 row and 0 columns 100
93


In [ ]:
arr[0][0]=50
arr

array([[50, 99],
       [98, 97],
       [96, 95],
       [94, 93],
       [92, 91]])

In [ ]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
print('sum of all elements of array',np.sum(mat))   # axis = 0 is vertical or columns  . axis =1 rows or acrros
print('max of all elements of array',np.max(mat))
print('min of all elements of array',np.min(mat))
print('cumsum of all elements of array',np.cumsum(mat))

sum of all elements of array 450
max of all elements of array 90
min of all elements of array 10
cumsum of all elements of array [ 10  30  60 100 150 210 280 360 450]


In [ ]:
print('sum of rows elements of array ',np.sum(mat,axis=1))
print('max of row elements of array',np.max(mat,axis=1))
print('min of row elements of array',np.min(mat,axis=1))
print('cumsum of row elements of array',np.cumsum(mat,axis=1))

sum of rows elements of array  [ 60 150 240]
max of row elements of array [30 60 90]
min of row elements of array [10 40 70]
cumsum of row elements of array [[ 10  30  60]
 [ 40  90 150]
 [ 70 150 240]]


In [ ]:
print('sum of column elements of array ',np.sum(mat,axis=0))
print('max of column elements of array',np.max(mat,axis=0))
print('min of column elements of array',np.min(mat,axis=0))
print('cumsum of column elements of array',np.cumsum(mat,axis=0))
print('mean of column elements of array',np.mean(mat,axis=0))

sum of column elements of array  [120 150 180]
max of column elements of array [70 80 90]
min of column elements of array [10 20 30]
cumsum of column elements of array [[ 10  20  30]
 [ 50  70  90]
 [120 150 180]]
mean of column elements of array [40. 50. 60.]


In [ ]:
# insert  , append and delete

In [ ]:
arr = np.array([10,20,30])
new_arr=np.append(arr,100)
print(new_arr)

[ 10  20  30 100]


In [ ]:
arr = np.array([10,20,30])
new_arr=np.append(arr,[51,41,31])
print(new_arr)

[10 20 30 51 41 31]


In [ ]:
iarr=np.insert(arr,1,300)  # array, index -- position to insert , value
print(iarr)

[ 10 300  20  30]


In [ ]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
iMat = np.insert(mat,1,100,axis=1)
print(iMat)

[[ 10 100  20  30]
 [ 40 100  50  60]
 [ 70 100  80  90]]


In [ ]:
iMat = np.insert(mat,1,[101,201,301],axis=1)
print(iMat)

[[ 10 101  20  30]
 [ 40 201  50  60]
 [ 70 301  80  90]]


In [ ]:
iMat = np.insert(mat,1,[[101,201,301],[401,501,601]],axis=1)
print(iMat)

[[ 10 101 401  20  30]
 [ 40 201 501  50  60]
 [ 70 301 601  80  90]]


In [ ]:
iMat = np.insert(mat,2,[101,201,301],axis=0)
print(iMat)

[[ 10  20  30]
 [ 40  50  60]
 [101 201 301]
 [ 70  80  90]]


In [ ]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
appendMat = np.append(mat,[[100,200,300],[400,500,600]],axis=0)
print(appendMat)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 200 300]
 [400 500 600]]


In [ ]:
appendMat = np.append(mat,[[100],[200],[300]],axis=1)
print(appendMat)


[[ 10  20  30 100]
 [ 40  50  60 200]
 [ 70  80  90 300]]


In [ ]:
mat2=np.arange(201,210)
mat2=np.reshape(mat2,(3,3))
mat2

array([[201, 202, 203],
       [204, 205, 206],
       [207, 208, 209]])

In [ ]:
appendMat2=np.append(mat,mat2,axis=0)
appendMat2

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209]])

In [ ]:
appendMat2=np.append(mat,mat2,axis=1)
appendMat2

array([[ 10,  20,  30, 201, 202, 203],
       [ 40,  50,  60, 204, 205, 206],
       [ 70,  80,  90, 207, 208, 209]])

In [ ]:
np.hstack((mat,mat2))

array([[ 10,  20,  30, 201, 202, 203],
       [ 40,  50,  60, 204, 205, 206],
       [ 70,  80,  90, 207, 208, 209]])

In [ ]:
np.vstack((mat2,mat))

array([[201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [ ]:
arr

array([10, 20, 30])

In [ ]:
new_arr=np.delete(arr,2)
print(new_arr)

[10 20]


In [ ]:
arr =np.array([10,20,30,50,60,70])
new_arr=np.delete(arr,[2,4])
print(new_arr)

[10 20 50 70]


In [ ]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.delete(mat,1,axis=0)

array([[10, 20, 30],
       [70, 80, 90]])

In [ ]:
np.delete(mat,1,axis=1)

array([[10, 30],
       [40, 60],
       [70, 90]])

In [ ]:
mat


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
mat[: ,: ]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
mat[0::2,:]

array([[10, 20, 30],
       [70, 80, 90]])

In [ ]:
mat[0::2,0:1]

array([[10],
       [70]])

In [ ]:
mat[1:,1:]

array([[50, 60],
       [80, 90]])

In [ ]:
mat[0::2,0::2]

array([[10, 30],
       [70, 90]])

In [ ]:
mat[::2,::2]

array([[10, 30],
       [70, 90]])

In [ ]:
mat[::,::-2]

array([[30, 10],
       [60, 40],
       [90, 70]])

In [ ]:
mat[0::-1,0::-1]

array([[10]])

In [ ]:
mat[1:0,1:0]  # mat[1:0:1,1:0:1]       +ve  left to right    in columns   ,   +ve step  top to bottom

array([], shape=(0, 0), dtype=int64)

In [ ]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# fancy index to select multiple elements  arr[[rows],[columns]]
mat[[0,1,2,1],[1,0,1,2]]

array([20, 40, 80, 60])

In [ ]:
mat[[0,1,2,2,1,1,0],[0,1,2,1,2,1,1]]

array([10, 50, 90, 80, 60, 50, 20])